#ddev-generated
volumes:
  redis:
    name: ddev-${DDEV_SITENAME}-redis
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}

services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:${DDEV_REDIS_VERSION:-6}-alpine
    command: /etc/redis/conf/redis.conf
    volumes:
      - '.:/mnt/ddev_config'
      - './redis:/etc/redis/conf'
      - 'redis:/data'
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
