name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '01 07 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Debug with tmate set "debug_enabled"'
        required: false
        default: "false"

defaults:
  run:
    shell: bash

env:
  # Allow ddev get to use a github token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Required permissions for keep-alive, used by ddev/github-action-add-on-test
permissions:
  actions: write

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Check shell options before and after disabling history expansion
      run: |
        echo "Before set +H: $-"
        set +H
        echo "1After set +H: $-"

    - uses: julienloizelet/ddev-add-on-test@b6b8c765ddba5fa511c2f9284e818d7fa3230f27
      with:
        ddev_version: ${{ matrix.ddev_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        debug_enabled: ${{ github.event.inputs.debug_enabled }}
        addon_repository: ${{ env.GITHUB_REPOSITORY }}
        addon_ref: ${{ env.GITHUB_REF }}
        #test_command: "bats tests --filter-tags !release"
